version: '3'
services:
  frontend:
    build:
      context: ./what-movie-client
      dockerfile: Dockerfile
    volumes:
      - ./what-movie-client/src:/app/src
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true

  backend:
    build:
      context: ./what-movie-server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - API_KEY=${API_KEY}
      - AUTHORIZATION=${AUTHORIZATION}
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
